var searchData=
[
  ['a_20benchmark_20for_20a_20new_20structure_0',['Adding a Benchmark for a New Structure',['../developer_guide.html#autotoc_md67',1,'']]],
  ['a_20glance_1',['Style Rules at a Glance',['../developer_guide.html#autotoc_md74',1,'']]],
  ['a_20new_20data_20structure_2',['a new data structure',['../developer_guide.html#autotoc_md79',1,'9. Adding a New Data Structure'],['../md_docs_2CONTRIBUTING.html#autotoc_md35',1,'Adding a New Data Structure']]],
  ['a_20new_20test_3',['Writing a New Test',['../developer_guide.html#autotoc_md60',1,'']]],
  ['a_20specific_20test_20or_20filter_4',['Run a Specific Test or Filter',['../developer_guide.html#autotoc_md58',1,'']]],
  ['a_20vulnerability_5',['Reporting a Vulnerability',['../md_docs_2SECURITY.html#autotoc_md143',1,'']]],
  ['about_20missing_20template_20instantiations_6',['Linker errors about missing template instantiations',['../developer_guide.html#autotoc_md106',1,'']]],
  ['add_20benchmarks_20in_20tt_20benchmarks_20benchmark_5fmain_20cpp_20tt_7',['Step 5 — Add benchmarks in &lt;tt&gt;benchmarks/benchmark_main.cpp&lt;/tt&gt;',['../developer_guide.html#autotoc_md84',1,'']]],
  ['add_20tests_20in_20tt_20test_5fsuite_20my_5fstructure_5ftest_5fcases_20cpp_20tt_8',['Step 4 — Add tests in &lt;tt&gt;test_suite/my_structure_test_cases.cpp&lt;/tt&gt;',['../developer_guide.html#autotoc_md83',1,'']]],
  ['adding_20a_20benchmark_20for_20a_20new_20structure_9',['Adding a Benchmark for a New Structure',['../developer_guide.html#autotoc_md67',1,'']]],
  ['adding_20a_20new_20data_20structure_10',['adding a new data structure',['../developer_guide.html#autotoc_md79',1,'9. Adding a New Data Structure'],['../md_docs_2CONTRIBUTING.html#autotoc_md35',1,'Adding a New Data Structure']]],
  ['after_20upload_11',['After Upload',['../developer_guide.html#autotoc_md98',1,'']]],
  ['all_20tests_20via_20ctest_20recommended_12',['Run All Tests via CTest (recommended)',['../developer_guide.html#autotoc_md56',1,'']]],
  ['allocate_13',['allocate',['../classstl__ext_1_1NodePool.html#a4ed65acc73f74f27615407384efd6fca',1,'stl_ext::NodePool']]],
  ['allocator_20tt_20nodepool_20t_20tt_14',['Arena Allocator (&lt;tt&gt;NodePool&lt;T&gt;&lt;/tt&gt;)',['../developer_guide.html#autotoc_md89',1,'']]],
  ['and_20verify_15',['Step 6 — Rebuild and verify',['../developer_guide.html#autotoc_md85',1,'']]],
  ['api_20documentation_16',['6. Generating API Documentation',['../developer_guide.html#autotoc_md69',1,'']]],
  ['architecture_17',['architecture',['../index.html#autotoc_md124',1,'Architecture'],['../md_docs_2README.html#autotoc_md25',1,'Architecture']]],
  ['architecture_20deep_20dive_18',['10. Architecture Deep-Dive',['../developer_guide.html#autotoc_md87',1,'']]],
  ['arena_20allocator_20tt_20nodepool_20t_20tt_19',['Arena Allocator (&lt;tt&gt;NodePool&lt;T&gt;&lt;/tt&gt;)',['../developer_guide.html#autotoc_md89',1,'']]],
  ['at_20a_20glance_20',['Style Rules at a Glance',['../developer_guide.html#autotoc_md74',1,'']]],
  ['at_20the_20bottom_20of_20tt_20cppx_20h_20tt_21',['Step 3 — Include the &lt;tt&gt;.tpp&lt;/tt&gt; at the bottom of &lt;tt&gt;cppx.h&lt;/tt&gt;',['../developer_guide.html#autotoc_md82',1,'']]],
  ['automatic_20formatting_22',['Automatic Formatting',['../developer_guide.html#autotoc_md72',1,'']]],
  ['avl_20tree_23',['Self-Balancing AVL Tree',['../index.html#autotoc_md117',1,'']]],
  ['avl_2etpp_24',['avl.tpp',['../avl_8tpp.html',1,'']]],
  ['avltree_25',['AVLTree',['../classstl__ext_1_1AVLTree.html',1,'stl_ext']]],
  ['avltree_3c_20t_20_3e_26',['AVLTree&lt; T &gt;',['../classstl__ext_1_1Node.html#a7cb909247f75f7e12f7d9af53b737377',1,'stl_ext::Node']]]
];
