var searchData=
[
  ['c_2023_20extended_20data_20structures_20library_0',['CPPX — C++23 Extended Data Structures Library',['../index.html',1,'']]],
  ['choices_1',['Design Choices',['../index.html#autotoc_md125',1,'']]],
  ['clang_20format_20tt_20not_20found_20—_20format_20target_20skipped_2',['&lt;tt&gt;clang-format&lt;/tt&gt; not found — format target skipped',['../developer_guide.html#autotoc_md102',1,'']]],
  ['class_20hierarchy_3',['Class Hierarchy',['../developer_guide.html#autotoc_md88',1,'']]],
  ['class_20in_20tt_20include_20cppx_20h_20tt_4',['Step 1 — Declare the class in &lt;tt&gt;include/cppx.h&lt;/tt&gt;',['../developer_guide.html#autotoc_md80',1,'']]],
  ['clean_20rebuild_5',['Clean Rebuild',['../developer_guide.html#autotoc_md53',1,'']]],
  ['clear_6',['clear',['../classstl__ext_1_1BinaryTree.html#afb627c57badd4a5d4c8b57a116f7589d',1,'stl_ext::BinaryTree']]],
  ['clock_7',['Clock',['../classBenchmark.html#af441761d55a8d6f42dfae17a0b7aec58',1,'Benchmark']]],
  ['clone_5fsubtree_8',['clone_subtree',['../classstl__ext_1_1BinaryTree.html#a46fd0b130e1649f302149b34856e12db',1,'stl_ext::BinaryTree']]],
  ['cmake_20fetchcontent_9',['cmake fetchcontent',['../index.html#autotoc_md114',1,'CMake FetchContent'],['../md_docs_2README.html#autotoc_md9',1,'Option 3 — CMake FetchContent']]],
  ['cmake_20options_20reference_10',['8. CMake Options Reference',['../developer_guide.html#autotoc_md76',1,'']]],
  ['cmake_20target_20recommended_11',['Run via CMake Target (recommended)',['../developer_guide.html#autotoc_md63',1,'']]],
  ['cmake_20targets_12',['CMake Targets',['../developer_guide.html#autotoc_md77',1,'']]],
  ['code_20guidelines_13',['Code Guidelines',['../md_docs_2CONTRIBUTING.html#autotoc_md36',1,'']]],
  ['code_20of_20conduct_14',['Code of Conduct',['../md_docs_2CODE__OF__CONDUCT.html',1,'']]],
  ['code_20style_15',['Code Style',['../md_docs_2README.html#autotoc_md22',1,'']]],
  ['code_20style_20formatting_16',['7. Code Style &amp; Formatting',['../developer_guide.html#autotoc_md71',1,'']]],
  ['code_5fof_5fconduct_2emd_17',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['color_18',['Color',['../namespacestl__ext.html#a1eb6d3460612b9fa0ff0ad48e124131a',1,'stl_ext']]],
  ['compute_5fsize_19',['compute_size',['../classstl__ext_1_1BinaryTree.html#a2d58bcdf0eae042748922efc00ca27af',1,'stl_ext::BinaryTree']]],
  ['conduct_20',['Code of Conduct',['../md_docs_2CODE__OF__CONDUCT.html',1,'']]],
  ['console_20tt_20print_5ftree_20tt_21',['Console (&lt;tt&gt;print_tree()&lt;/tt&gt;)',['../index.html#autotoc_md128',1,'']]],
  ['construction_22',['construction',['../md_docs_2README.html#autotoc_md15',1,'Manual Tree Construction'],['../index.html#autotoc_md120',1,'Manual Tree Construction']]],
  ['contains_23',['contains',['../classstl__ext_1_1BST.html#acb74ffc000a5efdb390fc3fb63ae62a8',1,'stl_ext::BST']]],
  ['contents_24',['Table of Contents',['../developer_guide.html#autotoc_md42',1,'']]],
  ['contributing_20to_20cppx_25',['Contributing to CPPX',['../md_docs_2CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_26',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['copy_27',['Header-Only (Copy)',['../index.html#autotoc_md112',1,'']]],
  ['copy_20into_20your_20project_28',['Option 1 — Header-only (copy into your project)',['../md_docs_2README.html#autotoc_md7',1,'']]],
  ['count_5fleaves_29',['count_leaves',['../classstl__ext_1_1BinaryTree.html#a3ad927cf9a94662c02770da704874e57',1,'stl_ext::BinaryTree']]],
  ['coverage_20by_20file_30',['Test Coverage by File',['../developer_guide.html#autotoc_md59',1,'']]],
  ['cpp_20tt_31',['cpp tt',['../developer_guide.html#autotoc_md83',1,'Step 4 — Add tests in &lt;tt&gt;test_suite/my_structure_test_cases.cpp&lt;/tt&gt;'],['../developer_guide.html#autotoc_md84',1,'Step 5 — Add benchmarks in &lt;tt&gt;benchmarks/benchmark_main.cpp&lt;/tt&gt;']]],
  ['cppx_32',['cppx',['../md_docs_2CONTRIBUTING.html',1,'Contributing to CPPX'],['../md_docs_2README.html',1,'CPPX']]],
  ['cppx_20—_20c_2023_20extended_20data_20structures_20library_33',['CPPX — C++23 Extended Data Structures Library',['../index.html',1,'']]],
  ['cppx_20developer_20guide_34',['CPPX Developer Guide',['../developer_guide.html',1,'']]],
  ['cppx_20h_20tt_35',['cppx h tt',['../developer_guide.html#autotoc_md80',1,'Step 1 — Declare the class in &lt;tt&gt;include/cppx.h&lt;/tt&gt;'],['../developer_guide.html#autotoc_md82',1,'Step 3 — Include the &lt;tt&gt;.tpp&lt;/tt&gt; at the bottom of &lt;tt&gt;cppx.h&lt;/tt&gt;']]],
  ['cppx_2eh_36',['cppx.h',['../cppx_8h.html',1,'']]],
  ['ctest_20recommended_37',['Run All Tests via CTest (recommended)',['../developer_guide.html#autotoc_md56',1,'']]],
  ['ctest_20tt_20says_20no_20tests_20found_38',['Tests pass but &lt;tt&gt;ctest&lt;/tt&gt; says &quot;no tests found&quot;',['../developer_guide.html#autotoc_md105',1,'']]],
  ['current_20data_20structures_39',['Current Data Structures',['../index.html#autotoc_md122',1,'']]]
];
