var searchData=
[
  ['t_20tt_0',['Arena Allocator (&lt;tt&gt;NodePool&lt;T&gt;&lt;/tt&gt;)',['../developer_guide.html#autotoc_md89',1,'']]],
  ['table_20of_20contents_1',['Table of Contents',['../developer_guide.html#autotoc_md42',1,'']]],
  ['takeaways_2',['takeaways',['../index.html#autotoc_md132',1,'Key Takeaways'],['../md_docs_2README.html#autotoc_md28',1,'Key Takeaways']]],
  ['target_20recommended_3',['Run via CMake Target (recommended)',['../developer_guide.html#autotoc_md63',1,'']]],
  ['target_20skipped_4',['&lt;tt&gt;clang-format&lt;/tt&gt; not found — format target skipped',['../developer_guide.html#autotoc_md102',1,'']]],
  ['targets_5',['CMake Targets',['../developer_guide.html#autotoc_md77',1,'']]],
  ['template_20instantiations_6',['Linker errors about missing template instantiations',['../developer_guide.html#autotoc_md106',1,'']]],
  ['test_7',['test',['../index.html#autotoc_md136',1,'Build &amp; Test'],['../md_docs_2README.html#autotoc_md20',1,'Build &amp; Test'],['../developer_guide.html#autotoc_md60',1,'Writing a New Test']]],
  ['test_20binary_20directly_8',['Run the Test Binary Directly',['../developer_guide.html#autotoc_md57',1,'']]],
  ['test_20coverage_20by_20file_9',['Test Coverage by File',['../developer_guide.html#autotoc_md59',1,'']]],
  ['test_20not_20fetching_10',['Google Test not fetching',['../developer_guide.html#autotoc_md101',1,'']]],
  ['test_20or_20filter_11',['Run a Specific Test or Filter',['../developer_guide.html#autotoc_md58',1,'']]],
  ['test_20suite_12',['4. Running the Test Suite',['../developer_guide.html#autotoc_md55',1,'']]],
  ['test_5fsuite_20my_5fstructure_5ftest_5fcases_20cpp_20tt_13',['Step 4 — Add tests in &lt;tt&gt;test_suite/my_structure_test_cases.cpp&lt;/tt&gt;',['../developer_guide.html#autotoc_md83',1,'']]],
  ['tests_20docs_14',['Standard Build (tests + docs)',['../developer_guide.html#autotoc_md49',1,'']]],
  ['tests_20found_15',['Tests pass but &lt;tt&gt;ctest&lt;/tt&gt; says &quot;no tests found&quot;',['../developer_guide.html#autotoc_md105',1,'']]],
  ['tests_20in_20tt_20test_5fsuite_20my_5fstructure_5ftest_5fcases_20cpp_20tt_16',['Step 4 — Add tests in &lt;tt&gt;test_suite/my_structure_test_cases.cpp&lt;/tt&gt;',['../developer_guide.html#autotoc_md83',1,'']]],
  ['tests_20or_20benchmarks_17',['Build Without Tests or Benchmarks',['../developer_guide.html#autotoc_md51',1,'']]],
  ['tests_20pass_20but_20tt_20ctest_20tt_20says_20no_20tests_20found_18',['Tests pass but &lt;tt&gt;ctest&lt;/tt&gt; says &quot;no tests found&quot;',['../developer_guide.html#autotoc_md105',1,'']]],
  ['tests_20via_20ctest_20recommended_19',['Run All Tests via CTest (recommended)',['../developer_guide.html#autotoc_md56',1,'']]],
  ['the_20binary_20directly_20',['Run the Binary Directly',['../developer_guide.html#autotoc_md64',1,'']]],
  ['the_20class_20in_20tt_20include_20cppx_20h_20tt_21',['Step 1 — Declare the class in &lt;tt&gt;include/cppx.h&lt;/tt&gt;',['../developer_guide.html#autotoc_md80',1,'']]],
  ['the_20test_20binary_20directly_22',['Run the Test Binary Directly',['../developer_guide.html#autotoc_md57',1,'']]],
  ['the_20test_20suite_23',['4. Running the Test Suite',['../developer_guide.html#autotoc_md55',1,'']]],
  ['the_20tt_20benchmark_20tt_20binary_20directly_20produces_20wrong_20output_20paths_24',['Running the &lt;tt&gt;benchmark&lt;/tt&gt; binary directly produces wrong output paths',['../developer_guide.html#autotoc_md104',1,'']]],
  ['the_20tt_20tpp_20tt_20at_20the_20bottom_20of_20tt_20cppx_20h_20tt_25',['Step 3 — Include the &lt;tt&gt;.tpp&lt;/tt&gt; at the bottom of &lt;tt&gt;cppx.h&lt;/tt&gt;',['../developer_guide.html#autotoc_md82',1,'']]],
  ['timepoint_26',['TimePoint',['../classBenchmark.html#a44b23ab1c2082b716dfc0dabf587d15e',1,'Benchmark']]],
  ['to_20cppx_27',['Contributing to CPPX',['../md_docs_2CONTRIBUTING.html',1,'']]],
  ['to_5fsorted_5fvector_28',['to_sorted_vector',['../classstl__ext_1_1RBTree.html#a7bcdbf68fc6508d7665335a9a1434bbe',1,'stl_ext::RBTree']]],
  ['tpp_20tt_29',['Step 2 — Implement in &lt;tt&gt;src/my_structure.tpp&lt;/tt&gt;',['../developer_guide.html#autotoc_md81',1,'']]],
  ['tpp_20tt_20at_20the_20bottom_20of_20tt_20cppx_20h_20tt_30',['Step 3 — Include the &lt;tt&gt;.tpp&lt;/tt&gt; at the bottom of &lt;tt&gt;cppx.h&lt;/tt&gt;',['../developer_guide.html#autotoc_md82',1,'']]],
  ['tree_31',['tree',['../md_docs_2README.html#autotoc_md14',1,'Binary Search Tree'],['../md_docs_2README.html#autotoc_md13',1,'Red-Black Tree'],['../index.html#autotoc_md117',1,'Self-Balancing AVL Tree']]],
  ['tree_20construction_32',['tree construction',['../index.html#autotoc_md120',1,'Manual Tree Construction'],['../md_docs_2README.html#autotoc_md15',1,'Manual Tree Construction']]],
  ['tree_20visualization_33',['tree visualization',['../index.html#autotoc_md127',1,'Tree Visualization'],['../md_docs_2README.html#autotoc_md17',1,'Tree Visualization']]],
  ['tree_20with_20validation_34',['Red-Black Tree with Validation',['../index.html#autotoc_md118',1,'']]],
  ['trees_35',['Self-Balancing Trees',['../md_docs_2README.html#autotoc_md12',1,'']]],
  ['troubleshooting_36',['12. Troubleshooting',['../developer_guide.html#autotoc_md100',1,'']]],
  ['tt_20benchmark_20tt_20binary_20directly_20produces_20wrong_20output_20paths_37',['Running the &lt;tt&gt;benchmark&lt;/tt&gt; binary directly produces wrong output paths',['../developer_guide.html#autotoc_md104',1,'']]],
  ['tt_20benchmarks_20benchmark_5fmain_20cpp_20tt_38',['Step 5 — Add benchmarks in &lt;tt&gt;benchmarks/benchmark_main.cpp&lt;/tt&gt;',['../developer_guide.html#autotoc_md84',1,'']]],
  ['tt_20clang_20format_20tt_20not_20found_20—_20format_20target_20skipped_39',['&lt;tt&gt;clang-format&lt;/tt&gt; not found — format target skipped',['../developer_guide.html#autotoc_md102',1,'']]],
  ['tt_20ctest_20tt_20says_20no_20tests_20found_40',['Tests pass but &lt;tt&gt;ctest&lt;/tt&gt; says &quot;no tests found&quot;',['../developer_guide.html#autotoc_md105',1,'']]],
  ['tt_20dot_20tt_20not_20found_41',['Doxygen warning: &lt;tt&gt;dot&lt;/tt&gt; not found',['../developer_guide.html#autotoc_md103',1,'']]],
  ['tt_20dump_5fto_5fdot_20tt_42',['Graphviz (&lt;tt&gt;dump_to_dot()&lt;/tt&gt;)',['../index.html#autotoc_md129',1,'']]],
  ['tt_20include_20cppx_20h_20tt_43',['Step 1 — Declare the class in &lt;tt&gt;include/cppx.h&lt;/tt&gt;',['../developer_guide.html#autotoc_md80',1,'']]],
  ['tt_20nodepool_20t_20tt_44',['Arena Allocator (&lt;tt&gt;NodePool&lt;T&gt;&lt;/tt&gt;)',['../developer_guide.html#autotoc_md89',1,'']]],
  ['tt_20print_5ftree_20tt_45',['Console (&lt;tt&gt;print_tree()&lt;/tt&gt;)',['../index.html#autotoc_md128',1,'']]],
  ['tt_20src_20my_5fstructure_20tpp_20tt_46',['Step 2 — Implement in &lt;tt&gt;src/my_structure.tpp&lt;/tt&gt;',['../developer_guide.html#autotoc_md81',1,'']]],
  ['tt_20test_5fsuite_20my_5fstructure_5ftest_5fcases_20cpp_20tt_47',['Step 4 — Add tests in &lt;tt&gt;test_suite/my_structure_test_cases.cpp&lt;/tt&gt;',['../developer_guide.html#autotoc_md83',1,'']]],
  ['tt_20tpp_20tt_20at_20the_20bottom_20of_20tt_20cppx_20h_20tt_48',['Step 3 — Include the &lt;tt&gt;.tpp&lt;/tt&gt; at the bottom of &lt;tt&gt;cppx.h&lt;/tt&gt;',['../developer_guide.html#autotoc_md82',1,'']]]
];
